# Memoria para el daemon de Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin
kotlin.code.style=official

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Habilita el Gradle Configuration Cache (compilaciones más rápidas)
org.gradle.configuration-cache=true
org.gradle.parallel=true
